### ISSUE TITLE
Add DescriptionList component

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#106]

**Comment by jurajhrib** [comment]
@michalkvasnicak 
Is this component really necessary? I have done a fast research and it appears this component is mostly used as a simpler table - and the only way to give it a nice clean style is using table styles.

Example: https://ant.design/components/descriptions/

Ant uses it as a table which is meant for simple data less than 25 items long. 

We can do it, but let's make an agreement about how is this going to work.

**Comment by michalkvasnicak** [comment]
I don't know, I was inspired by Polaris so dunno. :D Maybe you're right.
