### ISSUE TITLE
Utilize additional placements on Popover

### ISSUE THREAD

**Issue by jurajhrib** [Byteclaw/visage#120]
Popover accepts these values for placement:

  placement?:
    | 'top'
    | 'bottom'
    | 'left'
    | 'right'
    | 'top-left'
    | 'top-right'
    | 'bottom-left'
    | 'bottom-right';

But only the simple four are enabled right now. We should specify how it should render with the other four and utilize them in the positioning function.

**Comment by jurajhrib** [comment]
We need popover placement sandbox like MUI has :-)

<img width="863" alt="Screenshot 2020-01-03 at 10 58 14" src="https://user-images.githubusercontent.com/373788/71717310-fce1bf80-2e17-11ea-9588-81dd3f0f647c.png">

**Comment by michalkvasnicak** [comment]
This one is already done in alpha.19.
