### ISSUE TITLE
[AutocompleteInput,Select] Allow rendering additional textInput for fullscreen

### ISSUE THREAD

**Issue by jurajhrib** [Byteclaw/visage#121]
Allow rendering additional textInput for fullscreen and make sure it is focused when needed (on open?) and that values are synced between anchor textInput and fullscreen textInput.

**Comment by michalkvasnicak** [comment]
I think this one should be a special component that handles this. We shouldn't solve this for a user in core component.

**Comment by michalkvasnicak** [comment]
@jurajhrib please remove automatic full screen and let's make another component for that instead

**Comment by michalkvasnicak** [comment]
This one is already done. Fullscreen is disabled by default.
