### ISSUE TITLE
[TextInput] - conditional style sometimes does not work

### ISSUE THREAD

**Issue by jurajhrib** [Byteclaw/visage#186]
I want to set text input border only to bottom and conditionally change the color, like this

<img width="523" alt="Screenshot 2019-11-04 at 11 12 41" src="https://user-images.githubusercontent.com/373788/68113442-1f2c8f00-fef4-11e9-90c1-b390468006c7.png">

The color does not change accordingly.

**Comment by michalkvasnicak** [comment]
@jurajhrib is it hard to fix?

**Comment by michalkvasnicak** [comment]
@jurajhrib is this still relevant? could you please provide a test that reproduces this behaviour?

**Comment by jurajhrib** [comment]
@michalkvasnicak solved in the latest updates, closing issue
