### ISSUE TITLE
Add minimum widths to buttons?

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#204]
Something like `minWidth: 10ch` ?

![image](https://user-images.githubusercontent.com/174716/69045869-08a82c80-09f8-11ea-8dba-279ed92ca805.png)

**Comment by michalkvasnicak** [comment]
@jurajhrib what do you think?

**Comment by michalkvasnicak** [comment]
@jurajhrib this one is really something for discussion. I think it should have a min width because `Yes` `No` button look weird.

**Comment by jurajhrib** [comment]
Is this meant for all the buttons?

What about when you have an icon button?

But yes, I think we should have standardized sizes (ie small, medium, large, fullwidth)
and the size of small should also be the smallest possible size of button, which is not an "icon button" or "floating button".

**Comment by michalkvasnicak** [comment]
all buttons should have minWidth and icon button should be different component I think.

small, medium, large, fullWidth should be size variants on button.

**Comment by jurajhrib** [comment]
- min width should be a fallback size - which applies even when there's no characters etc
around 64px? or proportional to font sizes?

- size variants: small, medium, large

fullWidth can be achieved by width: 100% probably, so no need?
