### ISSUE TITLE
Components with click away handler cannot be more than once on the page

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#229]
Basically when you have an open drawer and inside this drawer is a popover. You can't close the popover, you'll close whole drawer.

Possible solution could be some ClickAway manager that registers current "active" component and closes it to manage depth.

**Comment by michalkvasnicak** [comment]
Or maybe the click away handler could stop propagation? Could it be enough to solve this?

**Comment by michalkvasnicak** [comment]
@jurajhrib what do you think? Possible solutions?

**Comment by jurajhrib** [comment]
I think stopPropagation is a way to go, if we can cover all use-cases with it. Otherwise we would probably need to implement some management mechanism for this, and that's prone to bugs.

**Comment by michalkvasnicak** [comment]
Is this solution viable? I mean, do we have a full control of zIndexes so we can guarantee that `stopPropagation` will actually help?

**Comment by michalkvasnicak** [comment]
This one is tricky because stopPropagation causes a problem e.g. you have a Popover which has backdrop but is invisible and you want to click on some interactive element that is outside of the Popover. You'll have to click twice because event propagation is stopped so the Popover will close but the interactive element won't be clicked.

**Comment by michalkvasnicak** [comment]
We could solve it by attaching click listener to `document` and check if the click happened inside a Modal or outside. But in that case I don't know how it will behave if you have stacked dialogs for example.

**Comment by michalkvasnicak** [comment]
Ok it's tricky... Popover doesn't have visible backdrop so it should use document.click to detect clickaway. Why? Let's see following screen.

![image](https://user-images.githubusercontent.com/174716/75686722-01521980-5c9d-11ea-8c4e-c62cc97bc1fd.png)

Basically when I click on search input nothing happens because there is an invisible backdrop rendered by Popover. So we need to detect if we have visible or invisible backdrop and base on that we should use document.click or backdrop click handlers to detect clickaway so we won't mess up the UX.

**Comment by michalkvasnicak** [comment]
This one is tricky. Components shouldn't rely on backdrop. Backdrop should be just visual thing that behaves as some sort of click blocker.

Popover for example should have any Backdrop and Modal should have backdrop only if backdrop is not disabled.

We should have some sort of click away management what basically invokes click handlers from deepest level to root level of an app and if handler stops propagation then parent handler is not called. In that case the component with backdrop stops the propagation to parent component but component like Popover shouldn't stop propagation because it doesn't have a backdrop!

**Comment by michalkvasnicak** [comment]
I'm trying a solution with standalone click away handler registry that is able to recognise if the component is fullscreen (Dialog with backdrop) or not (Menu).

Basically if component is fullscreen, we want to prevent closing all underlying component (e.g. stacked Dialogs, you want to close only top most Dialog) in other cases we want to close everything in the path (I don't know what would be  a possible example for this, basically a menu inside a popover or something like this. If you click outside of menu/popover you want to close both.

If you have Dialog with a backdrop and you have a Menu inside:

- if you click on backdrop, you want to close Dialog too not only Menu
- if you click on Dialog content outside of Menu, you want to close menu only

**Comment by michalkvasnicak** [comment]
The above mentioned behaviour should be possible by implementing the condition to all components with click away handlers that registers `click` handler to `document` if component doesn't have a backdrop (backdrop stops propagation so we can achieve desired behaviour easily)
