### ISSUE TITLE
[Menu] - should behave according to wai aria spec

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#251]
According to navigation menu, they should not be focusable using `Tab`

https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

https://www.w3.org/TR/wai-aria-practices-1.1/#wai-aria-roles-states-and-properties-13

According to both spec, `menuitem` should have `tabIndex = -1`

**Comment by michalkvasnicak** [comment]
@jurajhrib this one is tricky, I think based on spec, menu should not select next option when you press `Tab`. Instead Tab should go to next element in tab sequence and close the menu

**Comment by jurajhrib** [comment]
Okay, so we need to fix this then. So menu should not trap focus?

**Comment by michalkvasnicak** [comment]
Basically the problem is that menu button does not have according to spec. It should be able to open itself on <kbd>Arrow up</kbd> or <kbd>Arrow down</kbd> when it's focused. And should not focus menu items using <kbd>Tab</kbd>
