### ISSUE TITLE
[Effects] - use outlines instead of shadows for states like hove/focus...

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#260]

**Comment by michalkvasnicak** [comment]
This one is problematic because outline does not have border radius so it can break things.

Box shadow is also a problem if a user wants to use box shadow himself. How to deal with that? @jurajhrib

**Comment by jurajhrib** [comment]
@michalkvasnicak  Leave it as box shadow, if user wants to use custom box shadow, he will have to implement focus styles himself

**Comment by jurajhrib** [comment]
Closing for now. We can reopen if we bump into any tough problem.
