### ISSUE TITLE
[Menu] shows weird shadow where it renders the popup or portal

### ISSUE THREAD

**Issue by jurajhrib** [Byteclaw/visage#269]
<img width="1558" alt="Snímek obrazovky 2020-02-14 v 9 39 41" src="https://user-images.githubusercontent.com/373788/74515377-bd29ef80-4f0e-11ea-9218-3cb96b38fc1d.png">

@michalkvasnicak any idea why this happens? didnt have time to investigate

**Comment by michalkvasnicak** [comment]
@jurajhrib I think we had this problem in the past. It had something to do with anchor for the menu but I'm not sure.

**Comment by michalkvasnicak** [comment]
This is fixed, problem was that menu uses popover which uses modal and modal always renders backdrop. Now it renders backdrop only if modal is fixed
