### ISSUE TITLE
[Checkbox/Radio] - allow to provide custom element for toggler?

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#290]
This is a valid use case if people have their own design for checkbox / radio toggler. Only limitation is that it should compatible with logic behind it? Or maybe it chould be Component that receives `checked` prop so they can control the behaviour of it.

For example right now we have an svg and we are hiding the line and changing the color. But I had one edge case where the svg for checked checkbox was provided but the unchecked state was just a div with border.

**Comment by michalkvasnicak** [comment]
Possible API could be 

```
interface CheckboxProps {
  toggler?: ReactElement<{ checked: boolean }>;
}
```

It shouldn't be a breaking change at all.

**Comment by michalkvasnicak** [comment]
@jurajhrib what do you think?

**Comment by jurajhrib** [comment]
I mean, we can, but I would not complicate the code too much, because we are trying to keep the library lightweight. We can try to implement it, but I would not give this a high priority, because this is something that anyone can implement themselves with tools we provide.

**Comment by michalkvasnicak** [comment]
Yeah that's correct but I think that this one is basically just a replace of static toggler by "dynamic" one.
