### ISSUE TITLE
[CloseButton] - find out why close button styles are incorrectly extended

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#293]
```js
cons A = createComponent(CloseButton, {
	defaultStyles: {
      ml: 'auto',
      mb: 1,
    }
});
```

are not accepted

**Comment by jurajhrib** [comment]
@michalkvasnicak can you specify what happens? Or does it cause typescript error?

**Comment by michalkvasnicak** [comment]
@jurajhrib it'll ignore `ml` and `mb` and use the `my` and `ml` from `CloseButton` component.
