### ISSUE TITLE
[Menu,List] - renders unnecessary section element

### ISSUE THREAD

**Issue by jurajhrib** [Byteclaw/visage#333]
I've noticed, that menu renders completely unnecessary section element, which just copies most of the styles from the `ul` element, which is its child. 

I checked the List component code and it is a container component, which then wraps all the other things (listItemContainer and its items). This section container has no use in the List IMO, and thus can be removed from List render tree.

It might be handy in some nested lists, or maybe in the collapsible list (where it is used), so I kept the container on those places, but for simple List component, we do not need it.

I've checked some best practices and libraries, and it appears they do not render such thing.

Maybe @michalkvasnicak meant it for some use case (like I mentioned, nested lists), in which case, we can later implement some API to make use of it. Until then, I suggest removing it from the List render tree, so it does not mess up with Menu scrolling and events.

Also - I've noticed, that some libraries use completely separate List component for Menu (like MenuList in MUI), which could be another option, if somehow original List needs to be complicated.

**Comment by michalkvasnicak** [comment]
@jurajhrib  Yes I'd introduce new component only if it'll be needed. For now let's stick with what we have and remove unnecessary parts as you mentioned.
