### ISSUE TITLE
[Autocomplete/Select] - scroll focused item into view

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#336]

**Comment by jurajhrib** [comment]
This works in **Menu**, but Autocomplete and Select manage their events completely on their own, and they DO NOT apply real focus on the item. They just make it "active".

Scrolling is triggered when you really move focus, I think.


But when you apply focus(), you will lose focus from the TextInput, and thus lose typing ability. So we will probably need to make scrolling work somehow else - force the scroll event and emulate how browser does it? That sounds like a nasty code.

**Comment by michalkvasnicak** [comment]
In menu this works because it really uses `focus` but when we solve #251 we'll need to use the same logic there too.
