### ISSUE TITLE
[Colors] - design an API for color manipulation

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#339]
For example you have `lightAccent` color set to `#fff` in your theme. And you want to set an alpha channel in one particular place in your application. How'd you do that?

Something like this?

```ts
{
  color: 'alpha(lightAccent,0.8)'
}
```

or

```ts
{
  color: 'alpha(lightAccent, 80%)'
}
```

or something else? How could we use more than one function for manipulation?

**Comment by michalkvasnicak** [comment]
Maybe this could help us to get rid of `lightShadeOverlay` and `darkShadeOverlay` colors in theme palette. Something like `alpha(lightShades, 0.8)`

**Comment by michalkvasnicak** [comment]
We should maybe stick to `color-mod` from CSS 4 spec to be at least in some way familiar for developers.

**Comment by michalkvasnicak** [comment]
Is there a way to make it to the core without adding big dependencies? Or is it better to make it a standalone package with just color resolver that could be added to a theme (in that case we need to expose a way to define/override stylers/resolvers/formatters in existing theme creators).

What do you think @jurajhrib? I think I'll just finish this one so we can see how big will be the core package bundle size.

**Comment by jurajhrib** [comment]
I think if we'd support alpha(myColor, 0.8), that would be more than enough.

Would it work in all stylers? Borders, shadows, font color, backgrounds?

**Comment by jurajhrib** [comment]
The problem is, how to make it 100% universal (ie - would it work with all kinds of color definitions? Visage, rgb, rgba, hex, string?)

**Comment by michalkvasnicak** [comment]
Yes this one works in all color props. Only thing is that it doesn't support a `rgb()/rgba()` colors in `color` prop. Just `hex` or `color name`. But it's not problem to support `rgb/rgba`.

I can make the "language" in any form we want but we need to document. I'm proposing `alpha, ifDark, ifLight` functions so we can do at least these operations.

**Comment by michalkvasnicak** [comment]
But I think I'll keep syntax similar to `color-mod()` from CSS4. But we'll support only `alpha` and `ifDark/ifLight` unless I find a way how to make the parser smaller.
