### ISSUE TITLE
Add default theme

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#368]
We should consider making a `@byteclaw/visage-themes` just an additional package that is not necessary to start development. Some simple theme should be already a part of visage?

**Comment by michalkvasnicak** [comment]
@jurajhrib what do you think? This way we could make `theme` prop optional on `<DesignSystem />`

**Comment by jurajhrib** [comment]
That is my opinion, too. Theme should not bother you, unless you want to totally customise how it works. 

Themes package would be a collection of opinionated themes, which could even include third party libraries like color. Something like ColorizedTheme, or it would be just a flag in theme creator.

The themes would be hand picked for things like blogs (best typography and readability, scaling, contrast), web apps (maybe smaller fonts and more compacts sizing/spacing), presentation websites, Gatsby, etc.

**Comment by michalkvasnicak** [comment]
Yes but the problem is that our `visage-themes` package exposes 2 resolvers too. So maybe we'd need to move them to core (similar as `color`, etc) and `visage-themes` should just expose ready to use themes.

**Comment by michalkvasnicak** [comment]
I think that we can extract docs theme to visage package as a default theme for now. We'll need to move `boxShadow` parser to visage too because (maybe to core package? not sure). So we can finalize API for `DesignSystem` components.
