### ISSUE TITLE
[Visage] - allow to close Menu with the click on anchor button

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#383]
Basically if I click on anchor button when menu is opened I want to close it?

Try https://visage.design/components/navigation/menu click on Pop me and them again

**Comment by jurajhrib** [comment]
YES

**Comment by michalkvasnicak** [comment]
This one needs to be done on `Popover` level because Popover is responsible for registering click away handler.

Now the question is if this should be a default behaviour. I think that it should be because it's default behaviour you expect. So If the user clicks on anchor again, we want to close the Popover and not reopen it. 

Maybe this one can be somehow done by preventing default?

*This can't be done with `preventDefault` because we want to allow the user to click on underlying component*

**Comment by michalkvasnicak** [comment]
I'm not sure if this one is back again but in documentation for Menu it doesn't work but in the app it works correctly.

**Comment by michalkvasnicak** [comment]
It'd be better to have a test for this. I don't know whether jest-dom test would be sufficient or we need a cypress.

**Comment by michalkvasnicak** [comment]
This one is fixed
