### ISSUE TITLE
Add inverted variant of Message component

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#488]
Basically is non dismissable Message component that doesn't have a background color but a font color changes according to `variant`.

**Comment by michalkvasnicak** [comment]
Maybe we could add a `inverted` prop to `Message` instead of creating a new component.

**Comment by jurajhrib** [comment]
> Maybe we could add a `inverted` prop to `Message` instead of creating a new component.

That makes much more sense. Can you point me out to a real-life example of such Message variant?

**Comment by michalkvasnicak** [comment]
@jurajhrib I don't have a specific example (let's say from some website) but the possible usage could be to have an inline message below some element. For example InlineMessage can be used with TextInput to explain something.
